### ISSUE TITLE
Can't run the example code on my windows machine

### ISSUE THREAD

**Issue by ghost** [thekarel/best-practices-example#6]
'concurrently' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1        
npm ERR! cupcake@1.0.0 dev: `concurrently -n 'UI,GRAPH' 'graphUrl="http://localhost:8885" yarn ui dev' 'yarn graph dev'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cupcake@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thekarel** [comment]
Just to double check, have you ran `yarn` or `npm install` before?

**Comment by ghost** [comment]
> Just to double check, have you ran `yarn` or `npm install` before?

Yes, I have a successful run of yarn

**Comment by thekarel** [comment]
I've pushed a change that bumps concurrently to 5.3.0 -- let's hope it works on Windows! I only have access to a Mac at the moment so can't reproduce the issue.
